const constants = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  ADD_RECIPE: ' ADD_RECIPE',
  GET_ALL_RECIPES: 'GET_ALL_RECIPES',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  ADD_REVIEW: 'ADD_REVIEW',
  GET_FAV_RECIPES: 'GET_FAV_RECIPES',
  ADD_FAV_RECIPE: 'ADD_FAV_RECIPE',
  ERRORS: 'ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SIGN_IN_ERRORS: 'SIGN_IN_ERRORS',
  SIGN_UP_ERRORS: 'SIGN_UP_ERRORS',
  GET_USER_RECIPES: 'GET_USER_RECIPES',
  EDIT_USER_PROFILE: 'EDIT_USER_PROFILE',
  EDIT_RECIPE: 'EDIT_RECIPE',
  GET_RECIPES_REVIEWS: 'GET_RECIPES_REVIEWS',
  FIND_USERS: 'FIND_USERS',
  UPVOTE_RECIPE: 'UPVOTE_RECIPE',
  DOWNVOTE_RECIPE: 'DOWNVOTE_RECIPE',
  GET_SINGLE_RECIPE: 'GET_SINGLE_RECIPE',
  GET_LATEST_RECIPES: 'GET_LATEST_RECIPES'
};

export default constants;
