const constants = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  ADD_RECIPE: ' ADD_RECIPE',
  GET_ALL_RECIPES: 'GET_ALL_RECIPES',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  ADD_REVIEW: 'ADD_REVIEW',
  GET_FAV: 'GET_FAV',
  ADD_FAV: 'ADD_FAV',
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
  ERRORS: 'ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  SIGN_IN_ERRORS: 'SIGN_IN_ERRORS',
  SIGN_UP_ERRORS: 'SIGN_UP_ERRORS',
  GET_USER_RECIPES: 'GET_USER_RECIPES'
};

export default constants;
