const constants = {
  SIGN_UP: 'SIGN_UP',
  SIGN_IN: 'SIGN_IN',
  ADD_RECIPE: ' ADD_RECIPE',
  GET_ALL_RECIPES: 'GET_ALL_RECIPES',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  ADD_REVIEW: 'ADD_REVIEW',
  GET_FAV: 'GET_FAV',
  ADD_FAV: 'ADD_FAV',
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE'
};

export default constants;
