language: node_js

node_js:
  - stable

install:
  - npm install

env: 
  - NODE_ENV=test
  
before_script:
  - createdb more-recipes-test --username=postgres
  - sequelize db:migrate 

script:
  - npm test

after_success: npm run coveralls