engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
      linebreak-style:
        enabled: false
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
    paths:
      - "server/**/*.js"
languages:
  JavaScript: true
exclude_paths:
  - "node_modules/"
  - "client/"
  - "template/*"
  - "server/routes/"
  - "server/test"
  - "server/seeders"
  - "server/migrations"
  - "server/swagger.json"
  - "server/public/"